import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppinFont = Poppins({
  subsets: ["latin"],
  weight: "400",
  style: "normal",
  display: "swap",
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppinFont.variable}`}>{children}</body>
    </html>
  );
}
